models/boke.py
from . import ModelMixin
from . import db
from . import timestamp
from models.see import See


class Boke(db.Model, ModelMixin):
    __tablename__ = 'bokes'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100))
    content = db.Column(db.String(2000))
    created_time = db.Column(db.Integer, default=0)
    # 点赞，收藏，浏览数，评论数，标签，分类
    see_num = db.Column(db.Integer, default=0);
    star_num = db.Column(db.Integer, default=0);
    thumbs = db.Column(db.Integer, default=0);
    # 外键
    node_id = db.Column(db.Integer, db.ForeignKey('nodes.id'))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    # has relationship with comments
    comments = db.relationship('Comment', backref="boke")
    tags = db.relationship('Tag', backref='boke')
    star = db.relationship('Star', backref='boke');
    see = db.relationship('See', backref='boke');

    def __init__(self, form):
        self.title = form.get('title', '')
        self.content = form.get('content', '')
        self.created_time = timestamp()

    def see_add(self,ip):
        s = See.query.filter_by(boke_id=self.id, ip=ip).first()
        boke = self
        iv_time = 60
        if s == None:
            s_add = See(boke.id, ip)
            s_add.save()
            boke.see_num += 1
        else:
            if (timestamp() - s.created_time) > iv_time:
                boke.see_num += 1
                s.created_time = timestamp()
                s.save()

routes/boke.py
from models.boke import Boke
from models.star import Star
from routes import *


main = Blueprint('boke', __name__)

Model = Boke


@main.route('/')
@login_required
def index():
    u = current_user()
    ms = u.boke
    return render_template('boke.html', boke_list=ms, user_id=u.id)


@main.route('/new')
@login_required
def new():
    return render_template('boke_new.html')


@main.route('/<int:id>')
def show(id):
    m = Model.query.get(id)
    ip = request.remote_addr
    m.see_add(ip)
    m.save()
    u = current_user()
    star = Star.query.filter_by(user_id=u.id, boke_id=m.id).first()
    if star == None:
        star_flag = -1
    else:
        star_flag = star.flag
    return render_template('boke_index.html', boke=m,s_f=star_flag)


@main.route('/edit/<id>')
@login_required
def edit(id):
    t = Model.query.get(id)
    return render_template('boke_edit.html', todo=t)


@main.route('/add', methods=['POST'])
@login_required
def add():
    form = request.form
    m = Model(form)
    m.user_id = current_user().id
    m.save()
    return redirect(url_for('.index'))


@main.route('/update/<int:id>', methods=['POST'])
@login_required
def update(id):
    form = request.form
    t = Model.query.get(id)
    t.update(form)
    return redirect(url_for('.index'))


@main.route('/delete/<int:id>')
@login_required
def delete(id):
    t = Model.query.get(id)
    t.delete()
    return redirect(url_for('.index'))

routes/user.py
# from models.user import User
from routes import *


# 创建一个 蓝图对象 并且路由定义在蓝图对象中
# 然后在 flask 主代码中「注册蓝图」来使用
# 第一个参数是蓝图的名字，第二个参数是套路
main = Blueprint('user', __name__)
Model = User


def range_cookie(m=20):

    n = m
    s = ""
    for i in range(n):
        s += chr(97 + random.randint(0, 25))
    print("s cookie", s)
    return s


# def set_cookie_session(user):
#     cookie = range_cookie()
#     session[cookie] = user.id


@main.route('/')
def login_view():
    u = current_user()
    if u is not None:
        return redirect(url_for('boke.index', id=u.id))
    return render_template('login.html')


@main.route('register', methods=['POST'])
def register():
    form = request.form
    u = User(form)
    print(u.valid())
    cookie = ""
    if u.valid()[0]:
        u.save()
        cookie = range_cookie()
        session[cookie] = u.id
    else:
        abort(400)
    # 蓝图中的 url_for 需要加上蓝图的名字，这里是 user
    response = redirect(url_for('.login_view'))
    response.set_cookie('user_id', cookie)
    return response


@main.route('login', methods=['POST'])
def login():
    form = request.form
    print('from', form)
    u = User(form)
    print("login from", form, u)
    # 检查 u 是否存在于数据库中并且 密码用户 都验证合格
    user = User.query.filter_by(username=u.username).first()
    cookie = ""
    # if user is not None and user.validate_login(u):
    if u.valid_login(user):
        print('登录成功')
        cookie = range_cookie()
        session[cookie] = user.id
    else:
        print('登录失败')
    # 蓝图中的 url_for 需要加上蓝图的名字，这里是 user
    response = redirect(url_for('.login_view'))
    response.set_cookie('user_id', cookie)
    return response


@main.route('update', methods=['POST'])
def update():
    u = current_user()
    password = request.form.get('password', '123')
    if u.change_password(password):
        print('修改成功')
    else:
        print('用户密码修改失败')
    return redirect('/user/profile')


@main.route('profile', methods=['GET'])
def profile():
    u = current_user()
    if u is not None:
        print('profile', u.id, u.username, u.password)
        return render_template('profile.html', user=u)
    else:
        abort(401)


@main.route('logoff/<int:id>', methods=['GET'])
@login_required
def logoff(id):
    u = current_user()
    if u.id != id:
        print('注销用户失败')
        abort(404)
    else:
        cookie = request.cookies.get('user_id', None)
        del session[cookie]
        response = redirect(url_for('.login_view'))
        response.delete_cookie('user_id')
        print('注销用户成功 cookie', response.headers.__dict__)
    return response

templates/auth_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>auth</title>
</head>
<body>
    <div>
        <form action="{{ url_for('.login') }}" method="post">
            <input type="text" name="username" placeholder="输入 name">
            <input type="text" name="password" placeholder="输入 name">
            <button>login</button>
        </form>
    </div>
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>

    {% block css %}{% endblock %}
    <link rel="stylesheet" href="/static/css/font-awesome-4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="/static/css/base.css?q=wwww4">
    <script src="/static/js/jquery-3.0.0.min.js"></script>
    <script>    
        var log = function(a){
            console.log(a);
        }
        
        //<!-- ajax函数模板 -->
        var api = {}
        api.ajax = function(url, method, form, success, error) {
            
          var request = {
            url: url,
            type: method,
            data: form,
            success: function(response){
              //var r = JSON.parse(response)
              var r = response
              success(r);
            },
            error: function(err){
              log('网络错误', error)
              var r = {
                'success': false,
                message: '网络错误'
              }
              error(r)
            }
          }
          $.ajax(request)
        }
        
        api.get = function(url, success, error) {
          api.ajax(url, 'get', {}, success, error)
        }

        api.post = function(url, form, response) {
          api.ajax(url, 'post', form, response, response)
        }
        // <!-- 时间格式的转换函数 -->
        Date.prototype.Format = function (fmt) { //author: meizz
            var o = {
                "M+": this.getMonth() + 1, //月份
                "d+": this.getDate(), //日
                "H+": this.getHours(), //小时
                "m+": this.getMinutes(), //分
                "s+": this.getSeconds(), //秒
                "q+": Math.floor((this.getMonth() + 3) / 3), //季度
                "S": this.getMilliseconds() //毫秒
            };
            if (/(y+)/.test(fmt)){
                fmt = fmt.replace(RegExp.$1, (this.getFullYear() + "").substr(4 - RegExp.$1.length));
            }
            for (var k in o){
                if (new RegExp("(" + k + ")").test(fmt)){
                    fmt = fmt.replace(
                        RegExp.$1, (RegExp.$1.length == 1) ? (o[k]) : (("00" + o[k]).substr(("" + o[k]).length)));
                }
            }
            return fmt;
        }
        function init_time(cla,fmt){
            var base_time = $(cla);
            for (var i = 0; i < base_time.length; i++) {
                var num = Number($(base_time[i]).text());
                var time = new Date(num*1000);
                var fmt_str = time.Format(fmt);
                $(base_time[i]).text(fmt_str);
            }
        };
        // <!-- 初始化数据函数 -->
        function init_date(){
            // 初始化时间数据
            var cla = 'time';
            var fmt = 'yyyy-MM-dd'
            init_time(cla,fmt)
            // 初始化收藏状态
            init_star()
        };
        function init_star(){
            var flag = $("#star_flag").text();
            if(1 == Number(flag)){
                $('#short-button-star').addClass('color-blue-only');
                $('#short-button-star span').attr('flag','1');
            }
            else{
                $('#short-button-star span').attr('flag','-1');
            }
        }
        // 模拟from表单提交
        function form_post(url, PARAMTERS){
            var form = document.createElement("form");
            form.action = url;
            form.method = 'POST'
            form.display = 'none';
            form.target = "_self";
            //添加参数  //此为提交多个
            for (var item in PARAMTERS) {
                var opt = document.createElement("input");
                //设置 name 参数
                opt.name = item;
                opt.value = PARAMTERS[item];
                form.appendChild(opt);
            }
            document.body.appendChild(form);
            form.submit();
        };
        var __main = function() {
            // 实现书签位置，一会上，然后一会下,动画效果
            $(".book-mark-pos").on('click',function(){
                $('.book-mark-pos').css('top','-30px');
                setTimeout(function(){$('.book-mark-pos').css('top','-3px');}, "1000");
            });
            // 实现用户信息按钮的变化,三种状态，默认，聚焦，点击
             $('.sidebar-toggle').mouseenter(function(){ if($('.toggle-close')[0] == undefined)
                 {
                     // 当不存在关闭属性时，添加箭头属性
                     $('.sidebar-toggle').addClass('toggle-arrow');
                 }
                 });
             $('.sidebar-toggle').on('mouseleave',function(){$('.sidebar-toggle').removeClass('toggle-arrow');});
             $('.sidebar-toggle').on('click',function(){$('.sidebar-toggle').removeClass('toggle-arrow');$('.sidebar-toggle').toggleClass('toggle-close');});
            // 滚动条实现，侦听滚动事件
             $(document).scroll(function() {
                 var scroH = $(document).scrollTop(); //滚动高度
                 var viewH = $(window).height(); //可见高度
                 var contentH = $(document).height(); //内容高度
                 var nowf = scroH/(contentH-viewH)*100;
                 var nowi = parseInt(nowf);
                 var nowP = String(nowi)+'%';
                 $('.back-to-top span').text(nowP);
                 $('.reading-progress-bar').css('width',nowP);
                 // 实现当进度条大于1%时，显示下进度条
                 if(nowi>1){$('.back-to-top').addClass('back-to-on');}
                 else{$('.back-to-top').removeClass('back-to-on');};
              });
            // 重置滚动条进度为0，返回最顶部,.animate({属性:变化},时间)，指定一定时间内完成css变换
            $('.back-to-top').on('click',function(){$('html,body').animate({scrollTop: '0px'}, 300);});
            // sidebar的滚动出现
            $('.sidebar-toggle').on('click',function(){
                $('.boke-sidebar').toggleClass('boke-sidebar-active');
                $('body').toggleClass('boke-sidebar-active-body')
            });
            // 自动撑开的textarea
            $('.boke-comment-box').on('input','.textarea-grow',function(e) {
                var offsetHeight = e.target.offsetHeight;
                $(e.target).css('height', 'auto').css('height', e.target.scrollHeight  + 'px');
                if(e.target.offsetHeight !=  offsetHeight){
                    grow_height = e.target.offsetHeight - offsetHeight;
                    other_grow(grow_height);
                }
            });
            function px_to_number(str){
                return Number(str.slice(0,-2));
            }
            // 其他东西的位置，随之改变，这里是表情盒子
            function other_grow(gh){
                var e = $('.emoji-box');
                var emoji_top = px_to_number(e[0].style.top) + gh;
                e.css('top',emoji_top);
            };
            // {% block script %}{% endblock %}
            // 评论回复按钮点击，增加回复框
        }

        $(document).ready(function(){
            __main();
            init_date();
        });
    </script>



</head>
<body>
    <div class="other">
        <!-- // 滚动进度条上 -->
        <div class="reading-progress-bar" style="width: 0%;"></div>
        <!-- // 滚动进度条下 -->
        <div class="back-to-top back-to-top-on">
            <i class="fa fa-arrow-up"></i>
            <span>0%</span>
        </div>
        <!-- 用户sidebar的小图标 -->
        <div class="toggle sidebar-toggle">
            <span class="toggle-line toggle-line-first"></span>
            <span class="toggle-line toggle-line-middle"></span>
            <span class="toggle-line toggle-line-last"></span>
      </div>
      <!-- 书签按钮 -->
      <i role="button" class="fa fa-bookmark fa-2x book-mark-pos" aria-hidden="true"></i>
    </div>
    <div class="boke-top">
        <div class="boke-top-inner">
                <div class="boke-top-title">
                    <span class="login-line-top">
                    </span>
                    <a href="/boke">梁金辉2.0</a>
                    <span class="login-line-bto">
                    </span>
                </div>
                <nav class="boke-top-menu">
                    <ul class="list-no">
                        <li class="gua-nav-li">
                            <a class="gua-nav-link gua-active" href="/boke">首页</a>
                        </li>
                        <li class="gua-nav-li">
                            <a class="gua-nav-link" href="/user/">注册</a>
                        </li>
                        <li class="gua-nav-li">
                            <a class="gua-nav-link" href="/user/">登录</a>
                        </li>
                        <li class="gua-nav-li">
                            <a class="gua-nav-link" href="{{url_for('boke.new')}}">
                                发布新博客
                                <i class="fa fa-sort-desc icon-pl-3x" aria-hidden="true"></i>
                            </a>
                        </li>
                        <li class="gua-nav-li" style="float:right">
                            {% block logoff %}
                            {% endblock %}
                        </li>
                    </ul>
                </nav>
            </div>
            <a href="https://github.com/" class="github-corner" title="Follow me on GitHub" aria-label="Follow me on GitHub" rel="noopener" target="_blank">
                <svg width="80" height="80" viewBox="0 0 250 250" aria-hidden="true">
                    <path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"></path>
                    <path d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2" fill="currentColor" style="transform-origin: 130px 106px;" class="octo-arm"></path>
                    <path d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z" fill="currentColor" class="octo-body"></path>
                </svg>
            </a>
    </div>
    <div class="boke-main">
        <div class="boke-content boke-box">
            {% block content %}
            {% endblock %}
        </div>
        <div class="boke-sidebar">
            <div class="sidebar-inner">
                <div class="sidebar-auther">
                    <img src="\static\img\apple-touch-icon.png" class="auther-icon" alt="auther-icon">
                    <p class="auther-name">梁金辉</p>
                    <div class="auther-description">
                        一个喜欢看动漫的死宅
                    </div>
                </div>
                <div class="sidebar-census">
                    <nav>
                        <li>
                            <a href="11">
                                <span class="items-count">14</span>
                                <span class="items-name">博客</span>
                            </a>
                        </li>
                        <li>
                            <a href="11">
                                <span class="items-count">15</span>
                                <span class="items-name">分类</span>
                            </a>
                        </li>
                        <li>
                            <a href="11">
                                <span class="items-count">16</span>
                                <span class="items-name">标签</span>
                            </a>
                        </li>
                    </nav>
                </div>
                <div class="feed-link">
                    <a  href="">
                        <i class="fa fa-rss"></i>
                        <span>RSS</span>
                    </a>
                </div>
                <div class="sidebar-auther-link">
                    <span> <a href="11">GitHub</a></span>
                    <span> <a href="11">GitHub</a></span>
                    <span> <a href="11">GitHub</a></span>
                    <span> <a href="11">GitHub</a></span>
                    <span> <a href="11">GitHub</a></span>
                    <span> <a href="11">GitHub</a></span>
                </div>
                {% block sidebar %}
                <h1>hello </h1>
                {% endblock %}
            </div>
        </div>
    </div>
    <div class="boke-bottom a-bottom-1">
        <div class="boke-bottom-content boke-content-size">
            <div class="boke-bottom-ico">
                 <a href="#">粤ICP备********号</a>
            </div>
            <div class="boke-bottom-meta">
                <span>© 2013 – 2020</span>
                <span>
                    <span><i class="fa fa-user icon-p-3x"></i> </span>
                    <span>jinhui</span>
                </span>
            </div>
            <div class="boke-bottom-pageView">
                <span class="meta-item">
                    <span><i class="fa fa-user icon-pr-3x"></i></span>
                    <span>735268</span>
                </span>
                <span class="meta-item">
                    <span><i class="fa fa-eye icon-pr-3x"></i></span>
                    <span>2804336</span>
                </span>
            </div>
        </div>
    </div>
    <form id="base-post-form" action="" method="post" style="display:none">

    </form>
</body>
</html>

templates/boke.html
 {% extends "base.html" %}

{% block css %}
<link rel="stylesheet" href="/static/css/boke.css?q=qqqq8">
{% endblock %}

{% block title %}
{% endblock %}

{% block script %}


{% endblock %}

{% block logoff %}
<a class="gua-nav-link" href="{{ url_for('user.logoff', id=user_id) }}">注销</a>
{% endblock %}

{% block content %}
    <div class="bokes-inner-box">
        {% for boke in boke_list %}
        <div class="boke-inner">
            <div class="boke-title">
                <a class="boke-title-content" href="{{ url_for('.show', id=boke.id) }}">
                   【燕子集】{{boke.title}}
               </a>
            </div>
            <div class="boke-time-tag a-bottom-1">
                    <span class="meta-item">
                        <span class="icon-pr-3x"><i class="fa fa-calendar-o"></i></span>
                        <span>发表于</span>
                        <span><time>{{boke.created_time}}</time></span>
                    </span>
                    <span class="meta-item">
                        <span class="icon-pr-3x"><i class="fa fa-folder-o"></i></span>
                        <span>分类于</span>
                        <span>
                            <a href="#">
                                朝花夕拾
                            </a>
                        </span>
                    </span>
            </div>
            <div class="boke-summary">
                <p>{{boke.content}}</p>
            </div>
            <div class="more-content">
                <a href="{{url_for('.show', id=boke.id)}}">阅读全文 »</a>
            </div>
        </div>
        {% endfor %}
    </div>

{% endblock %}

templates/boke_new.html
{% extends "base.html" %}

{% block title %}
    发博客
{% endblock %}

{% block css %}
<link rel="stylesheet" href="/static/css/boke_new.css?q=qqqw2">
{% endblock %}

{% block script %}
    // 新博客添加
    $('#boke-submit-btn').on('click',function(){
        var title = $('#boke-new-title').val();
        var text = $('#boke-new-text').val();
        var datadirt = {'title':title, 'content':text};
        var url = '/boke/add';
        form_post(url, datadirt);});
{% endblock %}

{% block content %}
<div class="edit-box boke-comment-box">
    <div class="edit-title-box ">
        <textarea id='boke-new-title' rows='1' class="Input-title textarea-grow" name="title" placeholder="请输入标题（最多 30 个字）"></textarea>
    </div>
    <div class="edit-toolbar top-1-pale bottom-1-pale fa-2x">
        <i class="fa fa-bold" aria-hidden="true"></i>
        <i class="fa fa-italic" aria-hidden="true"></i>
        <i class="fa fa-underline" aria-hidden="true"></i>
        <i class="fa fa-header" aria-hidden="true"></i>
        <i class="fa fa-list-ol" aria-hidden="true"></i>
        <i class="fa fa-list-ul" aria-hidden="true"></i>
        <i class="fa fa-link" aria-hidden="true"></i>
        <i class="fa fa-font" aria-hidden="true"></i>
        <i class="fa fa-picture-o" aria-hidden="true"></i>
        <i class="fa fa-video-camera" aria-hidden="true"></i>
        <i class="fa fa-file" aria-hidden="true"></i>
        <i class="fa fa-subscript" aria-hidden="true"></i>
        <i class="fa fa-superscript" aria-hidden="true"></i>
    </div>
    <div class="edit-content" name="content">
        <textarea id="boke-new-text" rows='7' class="Input-txt textarea-grow " placeholder="请输入正文"></textarea>
    </div>
    <button id="boke-submit-btn" type="button" name="button" class="boke-submit-btn">发布</button>
</div>

{% endblock %}


{% block sidebar %}
    <h1>hello </h1>
<!--    <a href="/node/new">发布新帖子</a>-->
{% endblock %}

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
    <script src="/static/js/jquery-3.0.0.min.js"></script>
    <script src="/static/js/user.js?9"></script>
    <style>
       body
       {
           background-image: url(https://cdn.jsdelivr.net/gh/peterli110/pcrdfans_statics/background.jpg);
           background-attachment: fixed;
           background-size: cover;
       }
       .body_container
       {
           width: 600px;
           height: 700px;
           margin: 10px auto;
           display: flex;
           justify-content: center;
           align-items: center;
       }
       .item-border
       {
           border-width: 3px;
           border-color: orange;
           border-style: solid;
           border-radius: 30px;
       }
       /* .align-center{
           display: flex;
           justify-content: space-between;
           flex-direction: column;
           align-items: center
       } */
       .register-item-box
       {
           min-width: 300px;
           max-width: 400px;
           height: 350px;
           margin: 0 auto;
           padding: 40px 30px;
           background-color: rgb(255,255,255,0.8);
       }

       .page_login_ctn
       {
            margin:0 auto;
            height: 50px;
            font-size: 0px;
            width:fit-content;
       }
       .page_login_ctn .logo
       {
            width:40px;
            border-radius:50%;
            display: inline-block;
            vertical-align:middle
       }
       .page_login_ctn .title
       {
            font-size:18px;
            color:orange;
            margin-left:10px;
            white-space:nowrap;
            display: inline-block;
            vertical-align:middle
       }
       .global_register_title
       {
           font-size:30px;
           line-height:36px;
           margin:30px 0
       }
       /* .input-ant
       {
           width: inherit;
           height: 30px;
           margin: 30px auto: ;
           background: white;
       } */
       .input-icon
       {
           width: 13px;
           height: 13px;
           position: absolute;
           margin-left: 4px;
           margin-top: 12px;
       }
       .ant-input
       {
           padding-left: 25px;
           height: 30px;
           width: 300px;
           margin-bottom:30px;
           border-width: 1px;
           border-color: lightgray;
           border-style: solid;
           border-radius: 5px;

       }
       .ant-input:hover
       {
            border-color: orange;
       }
       .register-but
       {
           height: 30px;
           width: 330px;
           background: orange;
           border-width: 1px;

           border-color: orange;
           border-style: solid;
           border-radius: 5px;
           color: white;
           margin-bottom: 20px;
       }
       .register-but:hover
       {
           background: #FFCC33;
           border-color: #FFCC33;
           cursor: pointer;
       }
       a
       {
            color:orange;
            text-decoration:none;
       }
       a:hover
       {
           color:#FFCC33;
           cursor: pointer;
       }
   </style>

</head>
<body>
    <div class="body_container">
        <div class="register-item-box item-border">
            <div class="page_login_ctn">
                <a href="https://www.pcrdfans.com/signup">
                    <img src="/static/img/apple-touch-icon.png" class="logo" alt="logo">
                    <div class="title">公主连结Re: Dive Fan Club</div>
                </a>
            </div>
            <div class="register-box" >
                <div class="global_register_title">欢迎回来</div>
                <form id="post-from" action="/user/login" method="post">
                    <div>
                        <img src="/static/img/apple-touch-icon.png" class="input-icon" alt="username">
                        <input type="text" name="username" placeholder="用户名(区分大小写)" class="ant-input">
                    </div>
                    <div>
                        <input type="password" name="password" placeholder="密码" class="ant-input">
                    </div>
                    <div id="register-box" flag="0" hidden>
                        <div>
                            <input type="password" name="confirm" placeholder="确认密码" class="ant-input">
                        </div>
                        <div>
                            <label for="nickname" class="" >昵称（可选，将会在评论中显示）</label>
                            <br>
                            <input type="text" id="nickname" name="nickname" placeholder="昵称" class="ant-input">
                        </div>
                    </div>
                    <button class="register-but">登录</button>
                </form>
                <div id="to-login">没有账号？<!-- --> <a onclick="change_box_register()">去注册</a></div>
            </div>
        </div>
    </div>

</body>
</html>

templates/todo_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>todo edit</title>
</head>
<body>
    <div>
        <!-- action="/todo/update/{{todo.id}}" -->
        <form action="{{ url_for('.update', id=todo.id) }}" method="post">
            <input type="text" name="task" value="{{ todo.task }}">
            <button>更新</button>
        </form>
    </div>
</body>
</html>

templates/todo_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>todo</title>
    <style>
        form {
            display: inline-block;
        }
    </style>
</head>
<body>
    <div>
        <form action="{{ url_for('.add') }}" method="post">
            <input type="text" name="task" placeholder="输入 todo">
            <button>Add</button>
        </form>
    </div>

{% for todo in todo_list %}
    <div>
        <a href="{{ url_for('.edit', id=todo.id) }}">修改</a>
        <a href="{{ url_for('.delete', id=todo.id) }}">删除</a>
        {{ todo.task }}
    </div>
{% endfor %}

</body>
</html>